apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: {{K8S_NAMESPACE}}
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
